print('HelloWorld')
print('What is your name?')
name = input()
print('Hello ', name)
print('How old are you?')
a = input()
print('Harry Potter peron?')
b = input()
print('W wieku', a, 'nie ma sensu jechac na peron', b)
